### ISSUE TITLE
Invalid tuf-reposerver URL in startup.sh get_credentials function

### ISSUE THREAD

**Issue by ddunlap2005** [advancedtelematic/ota-community-edition#106]
If you are using /etc/hosts to perform your DNS resolution, you cannot resolve tuf-reposerver.ota.local until the 'make start' is complete. Also, need to do a case-insensitive search for x-ats-tuf-repo-id.

```
diff --git a/scripts/start.sh b/scripts/start.sh
index 9113b3a..8080a05 100755
--- a/scripts/start.sh
+++ b/scripts/start.sh
@@ -267,7 +267,8 @@ get_credentials() {

   http_2xx_or_4xx --ignore-stdin --check-status POST "${reposerver}/api/v1/user_repo" "${namespace}"

-  id=$(http --ignore-stdin --check-status --print=h GET http://tuf-reposerver.ota.local/api/v1/user_repo/root.json x-ats-namespace:default | grep x-ats-tuf-repo-id | awk '{print $2}' | tr -d '\r')
+  id=$(http --ignore-stdin --check-status --print=h GET "${reposerver}/api/v1/user_repo/root.json" "${namespace}" | grep -i x-ats-tuf-repo-id | awk '{print $2}' | tr -d '\r')
+  echo "id=${id}"

   http_2xx_or_4xx --ignore-stdin --check-status POST "${director}/api/v1/admin/repo" "${namespace}"

```

**Comment by msatpathy26** [comment]
@ddunlap2005, I tried with the suggested change above with a delay of 5s. It finally worked after days of trying :+1:

**Comment by ddunlap2005** [comment]
@msatpathy26 Glad you got it to work. The error you get without the sleep is:

```
Server: akka-http/10.1.11
X-Ats-Version: reposerver/0.7.1-22-g1d0d714

"63d416eb-8b3b-40b8-ad3f-a61282fd2270"


http: warning: HTTP 423 Locked

make: *** [start] Error 1
```

I tried a sleep of 2s and it still failed. I'm sure there is a better way to "delay" the function call but the 5s sleep works for now.

**Comment by msatpathy26** [comment]
@ddunlap2005 , by the way this is what works for me

-
-  id=$(http --ignore-stdin --check-status --print=h GET http://tuf-reposerver.ota.local/api/v1/user_repo/root.json x-ats-namespace:default | grep x-ats-tuf-repo-id | awk '{print $2}' | tr -d '\r')
+  sleep 5
+  id=$(http --ignore-stdin --check-status --print=h GET "${reposerver}/api/v1/user_repo/root.json" "${namespace}" | grep -i x-ats-tuf-repo-id | awk '{print $2}' | tr -d '\r')
+  echo "id=${id}"

**Comment by patrickvacek** [comment]
I happened to notice the same error recently. If you make a PR for the one line change to `id`, I'd be happy to merge it. I'm not sure the `sleep` is actually necessary. In my experience, you usually have to run `make start` a few times anyway.

**Comment by ddunlap2005** [comment]
#114 will resolve this issue. The sleep really is necessary. The `HTTP 423 Locked` error occurs every time without it. With the fix, I find `make start` very reliable to be honest.

**Comment by patrickvacek** [comment]
Improved by https://github.com/advancedtelematic/ota-community-edition/pull/114.
