### ISSUE TITLE
macOS specific: Illegal byte sequence returned when accessing /dev/urandom

### ISSUE THREAD

**Issue by ddunlap2005** [advancedtelematic/ota-community-edition#108]
The /dev/urandom device works a little differently under macOS than with Linux. In the configure_db_encryption function, the call to tr returns:

$ tr -cd '[:alnum:]' < /dev/urandom
tr: Illegal byte sequence
o%

In macOS, you need to prefix this call with LC_CTYPE=C (default is UTF-8) as documented in https://stackoverflow.com/questions/18953667/illegal-byte-sequence-error-while-using-shell-commands-in-mac-bash-terminal.

This diff to apply is:
```
diff --git a/scripts/start.sh b/scripts/start.sh
index 7534b26..ca3ec5a 100755
--- a/scripts/start.sh
+++ b/scripts/start.sh
@@ -225,7 +225,7 @@ configure_db_encryption() {
   ${KUBECTL} get secret "tuf-keyserver-encryption" &>/dev/null && return 0

   local salt=$(openssl rand -base64 8)
-  local key=$(tr -cd '[:alnum:]' < /dev/urandom | fold -w64 | head -n1)
+  local key=$(LC_CTYPE=C tr -cd '[:alnum:]' < /dev/urandom | fold -w64 | head -n1)

   ${KUBECTL} create secret generic "tuf-keyserver-encryption" \
     --from-literal="DB_ENCRYPTION_SALT=${salt}" \
```

**Comment by ddunlap2005** [comment]
#113 will resolve this issue.

**Comment by patrickvacek** [comment]
Fixed by https://github.com/advancedtelematic/ota-community-edition/pull/113.
