### ISSUE TITLE
start-services fails with http: NewConnectionError

### ISSUE THREAD

**Issue by msatpathy26** [advancedtelematic/ota-community-edition#111]
I tried to start the services following the instructions from contrib/gke/README.md.

Running  './contrib/gke/make SERVER_NAME=ota-ce.example.com DNS_NAME=example.com start-services' stops with the following error:
...
Waiting for keyserver
Waiting for keyserver
Waiting for keyserver
"4b8422a6-0f77-4219-b51d-3b24e0423a37"
http: error: ConnectionError: HTTPConnectionPool(host='tuf-reposerver.ota.local', port=80): Max retries exceeded with url: /api/v1/user_repo/root.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f574afa6790>: Failed to establish a new connection: [Errno -2] Name does not resolve')) while doing a GET request to URL: http://tuf-reposerver.ota.local/api/v1/user_repo/root.json

make: *** [Makefile:30: start_start-services] Error 1
make: Leaving directory '/src'

**Comment by ddunlap2005** [comment]
@msatpathy26 Look at the change I documented in issue #106. It fixes the URL which, likely works for the developers because they are using a proper name server. You will likely need to put a short sleep prior to this tuf call as well. Without the sleep, the id request fails.

**Comment by patrickvacek** [comment]
Fixed, or at least improved, by https://github.com/advancedtelematic/ota-community-edition/pull/114.
