### ISSUE TITLE
How to create client on Aktualizr on Ubuntu.

### ISSUE THREAD

**Issue by nakagawa4930** [advancedtelematic/ota-community-edition#118]
I want to create an OTA Community Edition client with Aktualizr on Ubuntu.
Only how to build a Yocto client is described here, but how do I create it with Aktualizr on Ubuntu?
I would like to know how to provisioning device credentials when using Aktualizr on Ubuntu.
It is stated that it is necessary to specify as follows in the Yocto environment.

`SOTA_CLIENT_PROV = "aktualizr-device-prov"`
`SOTA_DEPLOY_CREDENTIALS = "0"`
`SOTA_PACKED_CREDENTIALS = "/path/to/ota.ce/generated/credentials.zip"`

**Comment by houcros** [comment]
Not sure I understand, but maybe this is similar to what you're trying to do: https://docs.ota.here.com/getstarted/dev/qemuvirtualbox.html.

**Comment by nakagawa4930** [comment]
Thank you for your answer.
I'm checking the procedure manual for that URL.

**Comment by nakagawa4930** [comment]
The information I wanted was on the following site.
https://docs.ota.here.com/ota-client/latest/deb-package-install.html
