### ISSUE TITLE
gateway missing /core/system_info API endpoint

### ISSUE THREAD

**Issue by doanac** [advancedtelematic/ota-community-edition#56]
We've got our devices working pretty well with OTA-CE. One thing we are seeing now is that there is no hardware information showing up. A colleague has provided some logging from actualizr indicating its failing to make  a PUT call on /core/system_info. Looking at the gateway's nginx reverse proxy logic, it seems like a "core" path is needed and should probably route to some part of the device registry. Any ideas here?

**Comment by doanac** [comment]
So I've hacked together a "fix" by adding the following snippet my gateways nginx config. I have no idea if this is actually correct, but its working/secure:
~~~
   location /core/ {
        rewrite ^/core/(.*)$ /api/v1/mydevice/$deviceUuid/$1 break;
        #rewrite ^/core/(.*)$ /api/v1/devices/$1 break;
        #proxy_set_header x-ats-device-uuid $deviceUuid;
        proxy_set_header x-ats-namespace $deviceNamespace;
        proxy_pass http://device-registry;
      }
~~~

Please advice if this is correct.

**Comment by doanac** [comment]
So i've added some more hacks as our installed packages weren't showing up:
~~~
      location /core/system_info {
        rewrite ^/core/(.*)$ /api/v1/mydevice/$deviceUuid/$1 break;
        #rewrite ^/core/(.*)$ /api/v1/devices/$1 break;
        #proxy_set_header x-ats-device-uuid $deviceUuid;
        proxy_set_header x-ats-namespace $deviceNamespace;
        proxy_pass http://device-registry;
      }
      location /core/installed {
        rewrite ^/core/(.*)$ /api/v1/mydevice/$deviceUuid/packages break;
        #rewrite ^/core/(.*)$ /api/v1/devices/$1 break;
        #proxy_set_header x-ats-device-uuid $deviceUuid;
        proxy_set_header x-ats-namespace $deviceNamespace;
        proxy_pass http://device-registry;
      }

~~~

not sure if this is the correct way to do this?

**Comment by jerrytrieu** [comment]
Yes, that is correct. Can you open a pull request for this? Thanks!

**Comment by doanac** [comment]
Here you go: https://github.com/advancedtelematic/ota-community-edition/pull/60
