### ISSUE TITLE
0.4 keyserver migration?

### ISSUE THREAD

**Issue by doanac** [advancedtelematic/ota-community-edition#80]
Was wondering if there are plans for supporting the 0.4 keyserver's new [built-in encryption](https://github.com/advancedtelematic/libats/tree/master/libats-slick#configuration) in this project? I'm not sure how easy the migration is, and it sounds like it might break deployments that use offline keys?

**Comment by taheris** [comment]
Currently slightly older versions are pinned in `config/images.yaml`, but yes, we will upgrade to the latest version of all images (including the keyserver migration) shortly. I have some changes related to this on a local branch already but there are a couple of smaller issues to resolve first before I create a PR.
