### ISSUE TITLE
Director is broken with upstream Aktualizr

### ISSUE THREAD

**Issue by doanac** [advancedtelematic/ota-community-edition#89]
This change in aktualizr:

 https://github.com/advancedtelematic/aktualizr/commit/e458e890113232eeaa209c2ff584acbcaa625ccd

Requires this version of director:

  https://github.com/advancedtelematic/director/pull/120

I think its probably time to update some versions in images.yaml.

**Comment by taheris** [comment]
Hi, thanks for letting us know. I'm currently working on an alternative deployment model with Nix, which will hopefully be more stable than this to work with. I will create a PR for this repo when ready, although in the meantime I would suggest either using an older aktualizr version or alternatively you can try updating the services in `images.yaml` to `latest`.

**Comment by doanac** [comment]
We are having some people asking us what container versions they should be on. I can understand wanting to do different tooling, but its making hard for us to consume this project w/o a little guidance. Would it be possible to update this file for now?

**Comment by bclouser** [comment]
A list of known good versions that work together on the server side, as well as with Aktualizr would be nice. I am seeing a bunch of issues while trying to match compatibility with the version of aktualizr we have  running on our device, this being one of them (https://github.com/advancedtelematic/director/issues/147)

**Comment by simao** [comment]
Hi.

In terms of versions working together, all versions in master should work together as that is what we use in qa. If something does not work in master is usually reverted fairly quickly.

You can get the latest docker tag by just using `git rev-parse HEAD`, for example `advancedtelematic/treehub:<git HEAD>`.
