### ISSUE TITLE
user profile endpoint in ota-plus-server?

### ISSUE THREAD

**Issue by bclouser** [advancedtelematic/ota-community-edition#92]
Not an issue, just another question.

In the latest release of the ota-plus-server (5b1c352) there is a new (might not be that new) requirement to have an additional endpoint for user information.

The endpoint is described with these environment variables:
```
USER_PROFILE_HOST
USER_PROFILE_PORT
```

I stood up an endpoint and just blindly returned 200s, but that didn't seem to advance the UI which is still stuck asking for license agreement. Which might not be related... but one of the requests is a PUT/GET pair triggered on the agreement:
```
PUT /api/v1/users/default/contracts/tc%2F2018-04%2Fen%2Fterms-and-conditions.html 200
GET /api/v1/users/default/contracts 200 
```

I am wondering if I can get some guidance on what those endpoints need to do. Or if it is possible to just disable them entirely for development purposes?

Also, making issues to ask questions is perhaps not this project's desired approach... Should I instead be emailing someone? IRC?

Kind Regards,
   Ben

**Comment by eldojose** [comment]
Hi,
have you resolve this question? I'm face the same problem
