### ISSUE TITLE
gateway proxy logic?

### ISSUE THREAD

**Issue by doanac** [advancedtelematic/ota-community-edition#93]
This repo hasn't been updated in some time and during that time there have been updates to the backend services that require some nginx proxying logic in the gateway deployment. Would it be possible for you guys to share a redacted version of your production gateway nginx.conf? I can sort of figure it out by reading aktualizr code, and then looking at the source for the backend services, but I fear I could miss something subtle, but important.

thanks

**Comment by simao** [comment]
Hi.

We don't use nginx in production. Which endpoints are failing for you? 

Thanks

**Comment by simao** [comment]
See #102

**Comment by simao** [comment]
and #103
