### ISSUE TITLE
OSTree upload reported an error code:415 retrying... 

### ISSUE THREAD

**Issue by biswaranjan** [advancedtelematic/ota-community-edition#98]
Team, I need some suggestion on the following issues I am facing while trying out ota-community-edition.

Followed the steps to run ota-community-edition server on minikube with --kubernetes-version v1.15.6. (it seems the scripts are not compartible with kubernetes v1.17.x)

Issue #1: I see crypt-vault-bootstrap-job stays in "ContainerCreating" state always. Is this normal ?
crypt-vault-bootstrap-job-cx7c6         0/1     ContainerCreating   0          73m 

Issue #2:  Followed the instruction for HERE OTA Connect to build a QEMU client. However, if I integrate the credential files generated by ota-cmmunity-edition server, in my yocto build environment I run into following errors. Please note, the same build goes through, if I just change the credential files to the one generated from here.com.

Errors:
| > POST /api/v3/objects/e0/bead7be9323b06bea05cb9b66eb151839989e3a4e5d1a93e09a36919e91818.filez HTTP/1.1 
| Host: treehub.ota.local 
| User-Agent: garage-push/2019.11-0-g6633d0d0 
| Accept: */* 
| x-ats-ostree-force: true 
| Content-Type: application/octet-stream 
| Content-Length: 42 
|  
| * We are completely uploaded and fine 
| * Connection #56 to host treehub.ota.local left intact 
| OSTree upload reported an error code:415 retrying... 
| Http response code:415 
| The request's Content-Type is not supported. Expected: 
| multipart/form-data 
| Concurrency limit is now: 1 
| < HTTP/1.1 415 Unsupported Media Type 
| < Server: nginx/1.13.9 
| < Date: Tue, 03 Mar 2020 12:20:10 GMT 
| < Content-Type: text/plain; charset=UTF-8 
| < Content-Length: 74 
| < Connection: keep-alive 
| < x-ats-version: treehub/0.1.18 
| < 
| * Connection cache is full, closing the oldest one. 
| * Closing connection 58 
| * Connection #59 to host treehub.ota.local left intact 
| OSTree upload reported an error code:415 retrying... 
| Http response code:415 
| The request's Content-Type is not supported. Expected: 
| multipart/form-data 

And then the build fails. 

Environment:
minikube with --kubernetes-version v1.15.6
httpie, jq, kops are on latest released version.
Os: Ubuntu 16.04
Both Build machine and cluster are running on same HW.

Am I doing anything wrong or is this a known issue ?

**Comment by msatpathy26** [comment]
Even I am facing the exact same issue. Has anyone succeeded to fix/workaround this problem ?

**Comment by adlingepa** [comment]
I am also facing the exact same issue. Has anyone succeeded to fix/workaround this problem ?

**Comment by adlingepa** [comment]
Any updates on this? we are tried with all possible solutions, also upgraded Ubuntu OS version 16.04 to 18.04.
But we still having same error.

**Comment by msatpathy26** [comment]
Unfortunately, haven't heard anything on this yet. On older versions of aktualizr this issue was not faced. Downgrading aktualizr or re-tuning the mime types inside reverse proxy can be tried as a temporary workaround, until any fix is available for it.

**Comment by adlingepa** [comment]
@msatpathy26  Thank you for quick response. Appreciate your quick help.
Just want to know,
Which commit of the aktualizr we need to use, to remove this error and
Can you guide us that how to re-tune the mime types inside reverse proxy ?
(sorry I am totally unaware about that)

**Comment by simao** [comment]
Hi.

It looks like you'd need to upgrade treehub if you want to use an up to date version of aktualizr. Which version of aktualizr are you using?

**Comment by simao** [comment]
Let me know if the last update fix this, we might need to tweak gateway a bit more.

**Comment by simao** [comment]
Regarding issue 1 you point out I removed crypt-vault entirely, we don't need it anymore.

**Comment by adlingepa** [comment]
@simao 
I cleaned my environment, using make clean.
and tried with your latest commit #187e82e.
But now make start itself is failing.
I have reported error #104 for the same.

**Comment by adlingepa** [comment]
Thanks for Update @simao

Worked with the latest commit #4f0c895,
Thank you for your support.

**Comment by simao** [comment]
Thanks for the issue report!
